#!/bin/sh
#!/bin/sh
### BEGIN INIT INFO
# Short-Description: Start/stop the whole application
### END INIT INFO
<?php

$applink = trim(getenv('APPNAME_HOME').'/etc/init.d/'.strtolower(getenv('APPNAME')));
@unlink($applink);
@symlink(
  getenv('APPNAME_HOME').'/etc/init.d/appli',
  $applink
);
pkgi_track_instance($applink);

?>

case "$1" in
    start)
	echo -n "Starting $DESC: "
	<?php
	$dstart_list = unserialize(getenv('APPNAME_DSTART_LIST'));
	foreach($dstart_list as $module => $cmd) { ?>
            # Démarrage de <?php echo $module; ?> 
            <?php if (!is_array($cmd)) $cmd = array($cmd); ?>
            <?php foreach( $cmd as $c ) { ?>
		<?php echo getenv('APPNAME_HOME'); ?>/<?php echo $c; ?> 
            <?php } ?>
	    if [ ${?} -ne 0 ] ; then
		exit ${?}
	    fi
            echo "----"
	<?php } ?>	
	;;

    stop) 
	<?php
	$dstop_list = unserialize(getenv('APPNAME_DSTOP_LIST'));
	foreach($dstop_list as $module => $cmd) { ?>
	    # Arret de <?php echo $module; ?> 
            <?php if (!is_array($cmd)) $cmd = array($cmd); ?>
            <?php foreach( $cmd as $c ) { ?>
		<?php echo getenv('APPNAME_HOME'); ?>/<?php echo $c; ?> 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
            <?php } ?>
            echo "----"	    
	<?php } ?>
	;;
		
    restart) 
	<?php
	$drestart_list = unserialize(getenv('APPNAME_DRESTART_LIST'));
	foreach($drestart_list as $module => $cmd) { ?>
	    # Redemarrage de <?php echo $module; ?> 
            <?php if (!is_array($cmd)) $cmd = array($cmd); ?>
            <?php foreach( $cmd as $c ) { ?>
		<?php echo getenv('APPNAME_HOME'); ?>/<?php echo $c; ?> 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
            <?php } ?>
	    echo "----"
	<?php } ?>
	;;

    reload) 
    <?php
    $dreload_list = unserialize(getenv('APPNAME_DRELOAD_LIST'));
    foreach($dreload_list as $module => $cmd) { ?>
        # Redemarrage de <?php echo $module; ?> 
            <?php if (!is_array($cmd)) $cmd = array($cmd); ?>
            <?php foreach( $cmd as $c ) { ?>
        <?php echo getenv('APPNAME_HOME'); ?>/<?php echo $c; ?> 
                RCODE=${?}
        if [ ${RCODE} -ne 0 ]; then
            exit ${RCODE}
        fi
            <?php } ?>
        echo "----"
    <?php } ?>
    ;;

    status)
	<?php
	$dstatus_list = unserialize(getenv('APPNAME_DSTATUS_LIST'));
	foreach($dstatus_list as $module => $cmd) { ?>
            # Status de <?php echo $module; ?> 
            <?php if (!is_array($cmd)) $cmd = array($cmd); ?>
            <?php foreach( $cmd as $c ) { ?>
                <?php echo getenv('APPNAME_HOME'); ?>/<?php echo $c; ?> 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
	    <?php } ?>
	    echo "----"
	<?php } ?>
	;;

    *)
        # parametre invalide
	echo "usage: $0 ( start | stop | restart | status | help )"
	cat <<EOF

   start   - demarrage de <?php echo implode(', ',array_keys($dstart_list)); ?> 
   stop    - arret de <?php echo implode(', ',array_keys($dstop_list)); ?> 
   restart - redemarrage de  <?php echo implode(', ',array_keys($drestart_list)); ?> 
   status  - état de  <?php echo implode(', ',array_keys($drestart_list)); ?> 
   help    - cette page

EOF
	;;
esac

exit 0
