#!/bin/sh

PHPRAW="${PHP:=/usr/bin/php}"
PHP="${PHPRAW} -d short_open_tag=0 "
export PHP

FILE="`basename "$0"`"
DIR="`dirname "$0"`"
cd "$DIR"

# chargement des eventuels definitions d'environnements 
test -f "./pkgi.env" && . "./pkgi.env"
for i in `ls .` ; do
  test -f "$i/pkgi.env" && . "$i/pkgi.env"
done

# test de l'existance du binaire php en ligne de commande
PHPNOTFOUND=1
test -f "$PHPRAW" && PHPNOTFOUND=0
if [ $PHPNOTFOUND = 1 ]
then
    echo "php is not found, please install the php command line binary (php5-cli package on debian)"
    exit 1
fi

exec $PHP -C -q -d output_buffering=1 "$FILE" $@ 
exit $?
<?php
ob_end_clean();
set_time_limit(0);
ob_implicit_flush(true);

require_once dirname(__FILE__).'/pkgi.inc.php';

$pkgi = new Pkgi(null, realpath(dirname(__FILE__)), null, array_slice($_SERVER['argv'],1));
$pkgi->run();

?>
